### ISSUE TITLE
Implement and test contribution form

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/senar.ai#2]
## Overview

Implement the contribution form to substitute the current Google Form implementation.

Some parts of this epic is demonstrated in these talks:

* **Testing for Reliable Web Apps** talk: [_Pengujian untuk Aplikasi Web yang Andal_](https://alamisharia.co.id/acara/pengujian-untuk-aplikasi-web-yang-andal/) - [video recording](https://zainf.dev/het-4-recording).
* **Software Web Testing**: [_Pengujian Perangkat Lunak Web_](https://www.facebook.com/rr17x/posts/pfbid068qzcd2tvVUKVkLrLwApbktM5hsWTrcFJuqjhybRNh2BD7YdL65Vrgy3dAD4oudLl?__cft__[0]=AZXlBEILFOeeXaOgz0LgIbAT0W0zVCwZj_flRa72RbxGNMqt4EZTl12fq0dOjg4fiWN26AwwNs1WRbldLqJaD_7s9AbyMgo6LUgsJXOc7i3R1YSyZDpOM1ISMpP5KxM4LbuptBli4ak4sIkfdUedw_jU&__tn__=%2CO%2CP-R).

## Definition of Done

1. Implement a form to replace the [contribution form](https://senar.ai/go/form)
2. Implement a view to show the submitted form to the user
3. Write end-to-end tests to cover both implementations above

### Infrastructure Preparations

- [x] Database Integration
  - [x] [Compose SQLite database schema](https://github.com/senar-ai/web/issues/27)
  - [x] #3
  - [x] #5
- [x] End-to-end test integration
  - [x] #9
  - [x] #10
- [x] Unit & integration tests integration
  - [x] #12
  - [x] #13
  - [ ] Integrate [Jest Preview](https://www.jest-preview.com/), probably doesn't support [Vitest](https://vitest.dev) yet
- [x] Static analysis
  - [x] #15
  - [x] #16

### Features

- [x] Implementation
  - [x] #21
  - [x] #22
- [ ] Tests
  - [x] #23
  - [x] #24
- [ ] Approval mechanism
  - [ ] Implement basic authentication system
  - [ ] Gatekeep list contributions page
  - [ ] Provide actions for curating contributions
